"""
Generates deal_rationale/deal_memo.md and README.md from the model summary.

Nothing about the outcome is fixed prose: figures come from get_summary() and
the conclusions come from model/narrative.py, which is conditional on results.
"""

import os

from model.narrative import cr, fixed, is_negative, mult, pct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEMO_PATH = os.path.join(ROOT, "deal_rationale", "deal_memo.md")
README_PATH = os.path.join(ROOT, "README.md")
DASHBOARD_URL = "https://Yugdes.github.io/Adani-Ambuja-MA-Model/dashboard/index.html"


def _n(x, d=0):
    s = fixed(x, d)
    return f"({s})" if is_negative(x, d) else s


def _table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def build_memo(s):
    h, n, d, f = s["headline"], s["narrative"], s["deal"], s["financing"]
    o, g, v, syn = s["ownership"], s["goodwill"], s["value_creation"], s["synergies"]
    tr, inp, yrs = s["transaction"], s["inputs"], s["meta"]["years"]
    a, c = inp["ambuja_shares"], inp["acc_shares"]
    pf, ret = s["pro_forma"], s["returns"]
    prec = s["precedents"]

    uses = f["uses"]
    su = _table(["Sources", "₹ Cr", "Uses", "₹ Cr"], [
        ["Acquisition bridge loans", _n(f["sources"]["acq_bridge_loan"]), "Holcim stake in Ambuja", _n(uses["holcim_ambuja_stake"])],
        ["Acquisition term loans", _n(f["sources"]["acq_term_loan"]), "Holcim direct stake in ACC", _n(uses["holcim_acc_direct_stake"])],
        ["Sponsor equity (balancing)", _n(f["sources"]["sponsor_equity"]), "Open offers (Ambuja + ACC, as tendered)",
         _n(uses["ambuja_open_offer"] + uses["acc_open_offer"])],
        ["", "", "Transaction costs", _n(uses["transaction_costs"])],
        ["**Total**", f"**{_n(f['total_sources'])}**", "**Total**", f"**{_n(f['total_uses'])}**"],
    ])

    returns_tbl = _table(["", *yrs], [
        ["Adani-attributable net income (₹ Cr)", *[_n(r["attributable_net_income"]) for r in ret]],
        ["Return on sponsor equity", *[pct(r["roe_pct"]) for r in ret]],
        ["Cash ROIC on total investment", *[pct(r["cash_roic_pct"], 2) for r in ret]],
        ["Unlevered cost of capital", *[pct(r["unlevered_cost_of_capital_pct"], 2) for r in ret]],
        ["Dividends received / holdco interest", *[mult(r["dividend_interest_cover"], 2) for r in ret]],
        ["Sponsor top-up needed (₹ Cr)", *[_n(p["sponsor_top_up"]) for p in pf]],
    ])

    prec_rows = [[p["date"], f"{p['acquirer']} / {p['target']}", f"{fixed(p['capacity_mtpa'], 1)}", _n(p["ev_cr"]),
                  f"${fixed(p['ev_per_tonne_usd'], 0)}", p["note"] or ""] for p in prec["rows"]]
    prec_rows.append([tr["announcement_date"], "**Adani / Ambuja + ACC**", f"{fixed(s['valuation']['capacity_mtpa'], 1)}",
                      _n(s["valuation"]["enterprise_value"]), f"**${fixed(s['valuation']['ev_per_tonne_usd'], 0)}**", "This deal"])
    prec_rows.append(["", f"**Median, excl. distressed ({prec['count_ex_distressed']})**", "", "",
                      f"**${fixed(prec['median_usd_per_t_ex_distressed'], 0)}**", ""])
    prec_tbl = _table(["Date", "Acquirer / Target", "MTPA", "EV (₹ Cr)", "EV/t (US$)", "Note"], prec_rows)

    return f"""# Deal Memo: Adani Group Acquisition of Ambuja Cements & ACC

*Illustrative analysis from public information, written as at completion ({tr['completion_date']}). All figures are generated by the model in this repository (`python run_model.py`); INR crore unless stated.*

**Prepared by:** Yug Desai

---

## 1. Summary

**{n['verdict_title']}.**

- **Value:** {n['value_line']}
- **Returns:** {n['returns_line']}
- **Holdco:** {n['holdco_line']}

**Recommendation:** {n['recommendation']}

## 2. The Transaction

Holcim sold its {pct(a['holcim_stake_pct'], 2)} stake in Ambuja Cements and its {pct(c['holcim_direct_stake_pct'], 2)} direct stake in ACC to an Adani family SPV at ₹{fixed(a['offer_price'], 0)} and ₹{fixed(c['offer_price'], 0)} per share. Ambuja owns {pct(a['stake_in_acc_pct'], 2)} of ACC. Mandatory open offers for 26% of each company drew few acceptances because both shares traded above the offer price by completion. Only {fixed(a['open_offer_shares_tendered_cr'] * 100, 2)} lakh Ambuja shares and {fixed(c['open_offer_shares_tendered_cr'] * 100, 2)} lakh ACC shares were tendered.

Total consideration was {cr(d['total_consideration'])} (US${fixed(d['total_consideration_usd_bn'], 2)}bn at ₹{fixed(inp['fx']['inr_per_usd_at_close'], 2)}/US$; Adani reported US${fixed(d['reported_consideration_usd_bn'], 2)}bn). After the deal Adani owned {pct(o['adani_in_ambuja'] * 100, 2)} of Ambuja and controlled {pct(o['adani_controlled_in_acc'] * 100, 2)} of ACC, matching the {pct(tr['post_deal_ambuja_pct_reported'], 2)} and {pct(tr['post_deal_acc_pct_reported'], 2)} Adani reported. Its look-through economic interest in ACC is {pct(o['adani_lookthrough_in_acc'] * 100, 2)}.

**Premium.** The offers were {pct(d['premium_to_undisturbed_pct']['ambuja'])} (Ambuja) and {pct(d['premium_to_undisturbed_pct']['acc'])} (ACC) above the {tr['undisturbed_price_date']} undisturbed closes, a premium of {cr(d['premium_paid_cr'])} on the shares bought.

## 3. Financing

{su}

The reported US${fixed(tr['acq_debt_usd_bn'], 2)}bn of acquisition facilities from 14 banks sits in the offshore holdco, which leaves {cr(f['sources']['sponsor_equity'])} (US${fixed(f['sponsor_equity_usd_bn'], 2)}bn) of sponsor equity. Ambuja and ACC cash cannot fund the purchase: Indian company law bars financing the purchase of one's own shares, and minorities own {pct(o['nci_in_ambuja'] * 100, 0)} of Ambuja. Holdco loan-to-value is {pct(s['balance_sheet']['credit_at_close']['holdco_ltv_at_cost_pct'], 0)} at cost. Consolidated gross debt is {mult(s['balance_sheet']['credit_at_close']['gross_debt_to_ebitda'])} CY2021 EBITDA, or {mult(s['balance_sheet']['credit_at_close']['net_debt_to_ebitda'])} on a net basis.

## 4. Valuation and Precedents

At offer prices the combined enterprise value is {cr(s['valuation']['enterprise_value'])}: {mult(s['valuation']['ev_to_ebitda_cy2021'])} CY2021 EBITDA and US${fixed(s['valuation']['ev_per_tonne_usd'], 0)} per tonne of the {fixed(s['valuation']['capacity_mtpa'], 1)} MTPA capacity.

{prec_tbl}

{n['precedent_line']} Most precedents were asset or unlisted-company deals, so control premiums and EV/EBITDA are not comparable and are not shown.

## 5. Purchase Price Allocation

Goodwill is {cr(g['total_goodwill'])} ({pct(g['goodwill_pct_of_consideration'], 0)} of consideration): {cr(g['ambuja_goodwill'])} on Ambuja excluding its ACC stake and {cr(g['acc_goodwill'])} on ACC. It is computed on a look-through basis, with non-controlling interests measured at their share of identifiable net assets. Illustrative fair-value step-ups total {cr(s['ppa']['ambuja']['gross_step_up'] + s['ppa']['acc']['gross_step_up'])}. PP&E and finite intangibles are amortised over 15 years; brands are not amortised.

## 6. Synergies

Run-rate synergies of {cr(syn['run_rate'])} ({cr(syn['cost_run_rate'])} cost, {cr(syn['revenue_run_rate'])} revenue at EBITDA level) phase in over three years, with {cr(syn['costs_to_achieve_total'])} of one-off costs. These are model estimates, not company guidance. Discounted at the {pct(syn['discount_rate_pct'], 2)} unlevered cost of capital, the net NPV is {cr(syn['net_npv'])}; {pct(syn['terminal_value_share_pct'], 0)} of the gross value is terminal value. Adani captures {pct(v['adani_share_of_synergies_pct'], 0)} of synergies through its look-through stakes.

## 7. Returns

{returns_tbl}

- Holdco interest is assumed **not** tax-deductible: the borrower is an offshore SPV with no taxable income, and India has no tax consolidation. If it were deductible, {yrs[-1]} return on sponsor equity would be {pct(s['sensitivity']['interest_tax_shield'][1]['roe_final_year_pct'])}.
- Return on sponsor equity is compared with a {pct(h['levered_cost_of_equity_pct'])} cost of equity, relevered for the holdco's {mult(s['cost_of_capital']['holdco_debt_to_equity'], 2)} debt-to-equity.

## 8. Key Risks

1. **Holdco refinancing:** dividends cover only {mult(h['dividend_interest_cover_final_year'], 2)} of interest, so the structure depends on refinancing markets and sponsor liquidity. The debt is in US dollars and the dividends in rupees.
2. **Synergy delivery:** value creation needs at least {cr(v['breakeven_run_rate_synergies'])} of run-rate synergies.
3. **Margin cycle:** 2022 fuel-cost inflation compressed cement margins. Each 100bp of EBITDA margin moves {yrs[-1]} cash ROIC by about {fixed(abs(s['sensitivity']['ebitda_margin'][4]['cash_roic_final_year_pct'] - s['sensitivity']['ebitda_margin'][3]['cash_roic_final_year_pct']), 2)} percentage points.
4. **Minority leakage:** {pct(o['nci_lookthrough_in_acc'] * 100, 0)} of ACC's earnings belong to other shareholders, and every rupee of value moved between Ambuja and ACC is shared with minorities.

## 9. Limitations

The projections start from CY2021 audited standalone results with assumed growth and margins, and each projection year is treated as a full 12 months after completion. The 31-Dec-2021 balance sheets stand in for completion-date balances. PPA step-ups and synergies are illustrative. The value test treats the undisturbed share prices as fair standalone value, so it measures only whether synergies pay for the premium. The returns cover three years and are not a full DCF. Events after completion, such as the Adani family's ₹20,000 Cr preferential warrant subscription in Ambuja approved at completion, are excluded.
"""


def build_readme(s):
    h, n, tr = s["headline"], s["narrative"], s["transaction"]
    v, yrs = s["value_creation"], s["meta"]["years"]
    key = _table(["Metric", "Value"], [
        ["Consideration paid (Holcim stakes + open offers)", f"{cr(h['total_consideration'])} (US${fixed(h['total_consideration_usd_bn'], 2)}bn)"],
        ["Funding", f"{cr(h['acq_debt'])} holdco debt + {cr(h['sponsor_equity'])} sponsor equity"],
        ["Premium to undisturbed price (Ambuja / ACC)", f"{pct(h['premium_ambuja_pct'])} / {pct(h['premium_acc_pct'])}"],
        ["EV / EBITDA (CY2021) · EV / tonne", f"{mult(h['ev_to_ebitda_cy2021'])} · US${fixed(h['ev_per_tonne_usd'], 0)}"],
        ["Goodwill (look-through)", cr(h["total_goodwill"])],
        ["Run-rate synergies · net NPV", f"{cr(h['synergy_run_rate'])} · {cr(h['synergy_net_npv'])}"],
        ["Net value created for Adani (synergy NPV share − premium − costs)", cr(h["net_value_created"])],
        ["Breakeven run-rate synergies", cr(h["breakeven_run_rate_synergies"])],
        [f"Cash ROIC {h['final_year']} vs unlevered cost of capital", f"{pct(h['cash_roic_final_year_pct'])} vs {pct(h['unlevered_cost_of_capital_pct'], 2)}"],
        [f"Return on sponsor equity {h['final_year']} vs levered cost of equity", f"{pct(h['roe_final_year_pct'])} vs {pct(h['levered_cost_of_equity_pct'])}"],
        [f"Holdco dividend / interest cover {h['final_year']}", mult(h["dividend_interest_cover_final_year"], 2)],
    ])
    return f"""# Merger Consequences Model — Adani Group / Ambuja Cements & ACC

[![Dashboard](https://img.shields.io/badge/View-Dashboard-06b6d4?style=for-the-badge)]({DASHBOARD_URL})

Merger consequences analysis of the Adani Group's 2022 acquisition of Holcim's Indian cement business (Ambuja Cements and ACC). The model is built on filed financials and published deal terms. It covers purchase price allocation, look-through goodwill, minority interests, holdco financing, synergy value and returns.

## Conclusion

**{n['verdict_title']}.**

- {n['value_line']}
- {n['returns_line']}
- {n['holdco_line']}
- {n['precedent_line']}

## Key Outputs

{key}

*Every figure in this README, the memo, the dashboard and the workbook is generated by `python run_model.py`; the tests fail if any of them drift from the model.*

## Deal Facts

| | |
|---|---|
| Seller | {tr['seller']} |
| Buyer | {tr['acquirer']} |
| Announced / completed | {tr['announcement_date']} / {tr['completion_date']} |
| Combined capacity | {fixed(tr['combined_capacity_mtpa'], 1)} MTPA |
| Acquisition debt | US${fixed(tr['acq_debt_usd_bn'], 2)}bn from 14 banks |

## Methodology

1. **Deal and ownership.** Holcim's {pct(s['inputs']['ambuja_shares']['holcim_stake_pct'], 2)} of Ambuja and {pct(s['inputs']['acc_shares']['holcim_direct_stake_pct'], 2)} of ACC, plus open-offer shares actually tendered. The resulting stakes tie to Adani's reported {pct(tr['post_deal_ambuja_pct_reported'], 2)} / {pct(tr['post_deal_acc_pct_reported'], 2)}.
2. **Financing.** Reported US$ acquisition debt sits at the offshore holdco, with sponsor equity as the balancing source. Target cash is not used.
3. **PPA and goodwill.** Look-through: consideration is split between Ambuja ex-ACC and ACC at the offer prices, and goodwill is consideration less Adani's share of fair-value net assets (Ind AS 103 proportionate NCI).
4. **Projections.** CY2021 audited standalone base with assumed growth and margins. ACC dividends are removed from Ambuja's income as intra-group.
5. **Pro forma.** Consolidated (100%) earnings, attributed to Adani and non-controlling interests. Holdco interest gets no tax shield (offshore SPV), and the holdco cash schedule shows dividends against interest.
6. **Returns.** Return on sponsor equity vs relevered cost of equity, cash ROIC vs unlevered cost of capital, and a value test of Adani's share of synergy NPV vs premium paid plus costs.
7. **Sensitivities.** Every cell is a full re-run of the model: offer price × synergies, refinancing rate, EBITDA margin and tax deductibility.

## Deliverables

| File | What it is |
|---|---|
| `output/Adani_Ambuja_MA_Model.xlsx` | Live formula workbook: one Inputs sheet drives every calculation; a Checks sheet tests integrity and reconciles each formula with Python |
| `dashboard/index.html` | Web dashboard rendered entirely from `dashboard/model_data.js` |
| `deal_rationale/deal_memo.md` | Deal memo generated from the model |
| `output/summary.json` | Full model output |

## Project Structure

```
├── run_model.py               # Runs the model; writes Excel, JSON, dashboard data, memo and README
├── model/
│   ├── assumptions.py         # Every input, tagged [FILED] / [DERIVED] / [ASSUMPTION] with sources
│   ├── merger_model.py        # Calculations
│   ├── narrative.py           # Conclusions in words, conditional on results
│   ├── excel_generator.py     # Live-formula workbook
│   └── markdown_generator.py  # Memo and README
├── dashboard/                 # index.html, app.js, style.css, model_data.js (generated)
├── deal_rationale/deal_memo.md
├── output/                    # Workbook and summary.json (generated)
└── tests/                     # Integrity, input-sensitivity and cross-output consistency tests
```

## How to Run

```bash
pip install -r requirements.txt
python run_model.py        # regenerate every output
python -m pytest           # run the test suite
```

Open `dashboard/index.html` in a browser; no server is needed.

## Data Sources

{chr(10).join(f"- {v}" for v in s['sources'].values())}

Historical financials are standalone figures from company filings for the years ended 31 December 2019–2021. Projections, PPA step-ups, synergies, interest rates and cost-of-capital inputs are assumptions, each documented in `model/assumptions.py`.

## Author

**Yug Desai** — Mechanical Engineering, IIT Gandhinagar (Class of 2027). Interested in Investment Banking and Financial Analytics.

[LinkedIn](https://www.linkedin.com/in/yug-desai-9a227428b/) · [Email](mailto:yug.desai@iitgn.ac.in)

---
*Educational analysis from public information. Projections and assumptions are illustrative and are not investment advice.*
"""


def generate_markdown_files(model, summary=None):
    s = summary or model.get_summary()
    os.makedirs(os.path.dirname(MEMO_PATH), exist_ok=True)
    with open(MEMO_PATH, "w", encoding="utf-8") as f:
        f.write(build_memo(s))
    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(build_readme(s))
