"""
Runs the merger model and regenerates every output from a single source:

  output/summary.json                 full model output
  dashboard/model_data.js             the same data for the dashboard (window.MODEL)
  output/Adani_Ambuja_MA_Model.xlsx   live formula workbook
  deal_rationale/deal_memo.md         deal memo
  README.md                           project README
"""

import io
import json
import os
import sys

if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

from model.excel_generator import generate_excel_model  # noqa: E402
from model.markdown_generator import generate_markdown_files  # noqa: E402
from model.merger_model import MergerModel  # noqa: E402

SUMMARY_PATH = os.path.join(ROOT, "output", "summary.json")
DASHBOARD_DATA_PATH = os.path.join(ROOT, "dashboard", "model_data.js")
EXCEL_PATH = os.path.join(ROOT, "output", "Adani_Ambuja_MA_Model.xlsx")


def export_data(summary):
    os.makedirs(os.path.dirname(SUMMARY_PATH), exist_ok=True)
    payload = json.dumps(summary, indent=2, ensure_ascii=False)
    with open(SUMMARY_PATH, "w", encoding="utf-8") as f:
        f.write(payload + "\n")
    with open(DASHBOARD_DATA_PATH, "w", encoding="utf-8") as f:
        f.write("// Generated by run_model.py from the Python model. Do not edit by hand.\n")
        f.write(f"window.MODEL = {payload};\n")


def main():
    model = MergerModel()
    summary = model.get_summary()
    model.print_summary()

    export_data(summary)
    generate_excel_model(model, EXCEL_PATH)
    generate_markdown_files(model, summary)

    print("Outputs written:")
    for p in (SUMMARY_PATH, DASHBOARD_DATA_PATH, EXCEL_PATH,
              os.path.join(ROOT, "deal_rationale", "deal_memo.md"), os.path.join(ROOT, "README.md")):
        print("  ", os.path.relpath(p, ROOT))


if __name__ == "__main__":
    main()
