// Generated by run_model.py from the Python model. Do not edit by hand.
window.MODEL = {
  "meta": {
    "years": [
      "FY2023E",
      "FY2024E",
      "FY2025E"
    ],
    "currency": "INR crore",
    "base_year": "CY2021 (year ended 31-Dec-2021)",
    "notes": []
  },
  "headline": {
    "total_consideration": 51141.9289,
    "total_consideration_usd_bn": 6.4048,
    "acq_debt": 35932.5,
    "sponsor_equity": 15720.8481,
    "total_goodwill": 30218.8652,
    "ev_to_ebitda_cy2021": 13.9865,
    "ev_per_tonne_usd": 161.2765,
    "premium_ambuja_pct": 7.2125,
    "premium_acc_pct": 8.8345,
    "synergy_run_rate": 3100.0,
    "synergy_net_npv": 20622.4767,
    "net_value_created": 6708.9841,
    "breakeven_run_rate_synergies": 1310.3373,
    "final_year": "FY2025E",
    "cash_roic_final_year_pct": 6.6663,
    "unlevered_cost_of_capital_pct": 12.775,
    "roe_final_year_pct": 1.4253,
    "levered_cost_of_equity_pct": 25.8279,
    "earns_cost_of_capital_any_year": false,
    "earns_cost_of_equity_any_year": false,
    "dividend_interest_cover_final_year": 0.1226
  },
  "transaction": {
    "deal_name": "Adani Group acquisition of Ambuja Cements & ACC from Holcim",
    "acquirer": "Endeavour Trade and Investment Ltd (Adani family SPV, Mauritius)",
    "seller": "Holcim Group",
    "announcement_date": "15-May-2022",
    "completion_date": "16-Sep-2022",
    "undisturbed_price_date": "13-May-2022",
    "balance_sheet_date": "31-Dec-2021",
    "combined_capacity_mtpa": 67.5,
    "consideration_usd_bn_reported": 6.5,
    "acq_debt_usd_bn": 4.5,
    "post_deal_ambuja_pct_reported": 63.15,
    "post_deal_acc_pct_reported": 56.69
  },
  "inputs": {
    "fx": {
      "inr_per_usd_at_close": 79.85
    },
    "ambuja_shares": {
      "total_shares_cr": 198.56,
      "holcim_stake_pct": 63.11,
      "open_offer_shares_tendered_cr": 0.0727,
      "offer_price": 385.0,
      "undisturbed_close": 359.1,
      "close_at_completion": 516.7,
      "stake_in_acc_pct": 50.05
    },
    "acc_shares": {
      "total_shares_cr": 18.78,
      "holcim_direct_stake_pct": 4.48,
      "open_offer_shares_tendered_cr": 0.4061,
      "offer_price": 2300.0,
      "undisturbed_close": 2113.3,
      "close_at_completion": 2611.5
    },
    "deal_costs": {
      "transaction_costs_pct_of_consideration": 1.0
    },
    "acq_debt": {
      "bridge_usd_bn": 3.5,
      "term_rate_pct": 7.5,
      "bridge_rate_pct": 8.0,
      "refi_rate_pct": 7.5,
      "interest_tax_deductible": false
    },
    "holdco": {
      "wht_on_ambuja_dividends_pct": 5.0,
      "wht_on_acc_dividends_pct": 15.0
    },
    "projection": {
      "years": [
        "FY2023E",
        "FY2024E",
        "FY2025E"
      ],
      "ambuja_revenue_growth_pct": [
        12.0,
        9.0,
        8.0
      ],
      "acc_revenue_growth_pct": [
        12.0,
        9.0,
        8.0
      ],
      "ambuja_ebitda_margin_pct": [
        18.0,
        20.0,
        21.0
      ],
      "acc_ebitda_margin_pct": [
        12.0,
        14.0,
        15.0
      ],
      "tax_rate_pct": 25.17,
      "dividend_payout_pct": 20.0
    },
    "cost_of_capital": {
      "risk_free_pct": 7.25,
      "equity_risk_premium_pct": 6.5,
      "asset_beta": 0.85,
      "synergy_terminal_growth_pct": 4.0
    },
    "intercompany": {
      "acc_dps_paid_in_cy2021": 14.0
    }
  },
  "historicals": {
    "ambuja": {
      "years": [
        "CY2019",
        "CY2020",
        "CY2021"
      ],
      "revenue": [
        11668.0,
        11372.0,
        13979.0
      ],
      "operating_expenses": [
        9519.0,
        8725.0,
        10764.0
      ],
      "ebitda": [
        2149.0,
        2647.0,
        3215.0
      ],
      "other_income_normal": [
        424.0,
        371.0,
        281.0
      ],
      "exceptional_items": [
        3.0,
        1.0,
        -66.0
      ],
      "interest_expense": [
        84.0,
        83.0,
        91.0
      ],
      "depreciation": [
        544.0,
        521.0,
        552.0
      ],
      "pbt": [
        1948.0,
        2414.0,
        2788.0
      ],
      "net_income": [
        1529.0,
        1790.0,
        2083.0
      ],
      "eps": [
        7.7,
        9.02,
        10.49
      ],
      "dividend_payout_pct": [
        19.0,
        200.0,
        60.0
      ]
    },
    "acc": {
      "years": [
        "CY2019",
        "CY2020",
        "CY2021"
      ],
      "revenue": [
        15657.0,
        13785.0,
        16151.0
      ],
      "operating_expenses": [
        13247.0,
        11432.0,
        13151.0
      ],
      "ebitda": [
        2409.0,
        2352.0,
        3000.0
      ],
      "other_income_normal": [
        287.0,
        204.0,
        203.0
      ],
      "exceptional_items": [
        24.0,
        -176.0,
        -91.0
      ],
      "interest_expense": [
        86.0,
        57.0,
        55.0
      ],
      "depreciation": [
        603.0,
        635.0,
        597.0
      ],
      "pbt": [
        2031.0,
        1688.0,
        2460.0
      ],
      "net_income": [
        1359.0,
        1415.0,
        1820.0
      ],
      "eps": [
        72.36,
        75.35,
        96.93
      ],
      "dividend_payout_pct": [
        19.0,
        19.0,
        60.0
      ]
    },
    "ambuja_bs": {
      "share_capital": 397.0,
      "reserves": 21808.0,
      "borrowings": 351.0,
      "other_liabilities": 5627.0,
      "fixed_assets": 7671.0,
      "cwip": 951.0,
      "investments": 11774.0,
      "inventories": 1464.0,
      "trade_receivables": 295.0,
      "cash": 4169.0,
      "other_assets": 1859.0,
      "total_assets": 28183.0
    },
    "acc_bs": {
      "share_capital": 188.0,
      "reserves": 14040.0,
      "borrowings": 126.0,
      "other_liabilities": 6565.0,
      "fixed_assets": 6723.0,
      "cwip": 1212.0,
      "investments": 193.0,
      "inventories": 1273.0,
      "trade_receivables": 462.0,
      "cash": 7403.0,
      "other_assets": 3653.0,
      "total_assets": 20919.0
    }
  },
  "deal": {
    "shares_acquired_cr": {
      "holcim_ambuja": 125.3112,
      "open_offer_ambuja": 0.0727,
      "holcim_acc": 0.8413,
      "open_offer_acc": 0.4061
    },
    "consideration_by_component": {
      "holcim_ambuja": 48244.8182,
      "open_offer_ambuja": 27.9895,
      "holcim_acc": 1935.0912,
      "open_offer_acc": 934.03
    },
    "consideration_ambuja_shares": 48272.8077,
    "consideration_acc_shares": 2869.1212,
    "total_consideration": 51141.9289,
    "transaction_costs": 511.4193,
    "total_uses": 51653.3481,
    "total_consideration_usd_bn": 6.4048,
    "reported_consideration_usd_bn": 6.5,
    "premium_to_undisturbed_pct": {
      "ambuja": 7.2125,
      "acc": 8.8345
    },
    "premium_paid_cr": 3480.3412,
    "market_value_of_stakes_at_completion": 68043.5694,
    "offer_vs_completion_price_pct": {
      "ambuja": -25.4887,
      "acc": -11.928
    }
  },
  "ownership": {
    "adani_in_ambuja": 0.6315,
    "adani_direct_in_acc": 0.0664,
    "ambuja_in_acc": 0.5005,
    "adani_lookthrough_in_acc": 0.3825,
    "adani_controlled_in_acc": 0.5669,
    "nci_in_ambuja": 0.3685,
    "nci_lookthrough_in_acc": 0.6175
  },
  "financing": {
    "sources": {
      "sponsor_equity": 15720.8481,
      "acq_term_loan": 7985.0,
      "acq_bridge_loan": 27947.5
    },
    "uses": {
      "holcim_ambuja_stake": 48244.8182,
      "holcim_acc_direct_stake": 1935.0912,
      "ambuja_open_offer": 27.9895,
      "acc_open_offer": 934.03,
      "transaction_costs": 511.4193
    },
    "total_sources": 51653.3481,
    "total_uses": 51653.3481,
    "acq_debt_total": 35932.5,
    "sponsor_equity_usd_bn": 1.9688,
    "debt_pct_of_sources": 69.5647
  },
  "cost_of_capital": {
    "unlevered_cost_of_capital_pct": 12.775,
    "holdco_debt_to_equity": 2.3625,
    "levered_beta": 2.8581,
    "levered_cost_of_equity_pct": 25.8279
  },
  "ppa": {
    "ambuja": {
      "step_ups": {
        "ppe": 3200.0,
        "mineral_rights": 4500.0,
        "brand": 2800.0,
        "customer_relationships": 1200.0,
        "favourable_contracts": 650.0,
        "inventory": 180.0
      },
      "gross_step_up": 12530.0,
      "deferred_tax_liability": 3153.801,
      "book_equity": 22205.0,
      "investment_eliminated": 11774.0,
      "fv_net_identifiable_assets": 19807.199,
      "annual_amortisation": 636.6667,
      "inventory_release_year1": 180.0
    },
    "acc": {
      "step_ups": {
        "ppe": 2800.0,
        "mineral_rights": 3800.0,
        "brand": 2200.0,
        "customer_relationships": 950.0,
        "favourable_contracts": 420.0,
        "inventory": 220.0
      },
      "gross_step_up": 10390.0,
      "deferred_tax_liability": 2615.163,
      "book_equity": 14228.0,
      "investment_eliminated": 0.0,
      "fv_net_identifiable_assets": 22002.837,
      "annual_amortisation": 531.3333,
      "inventory_release_year1": 220.0
    }
  },
  "goodwill": {
    "acc_equity_value_at_offer_100pct": 43194.0,
    "ambuja_equity_value_at_offer_100pct": 76445.6,
    "acc_value_in_ambuja_purchase": 13651.4119,
    "consideration_ambuja_ex_acc": 34621.3957,
    "consideration_acc_lookthrough": 16520.5331,
    "adani_share_fv_ambuja": 12507.5754,
    "adani_share_fv_acc": 8415.4882,
    "ambuja_goodwill": 22113.8203,
    "acc_goodwill": 8105.0449,
    "total_goodwill": 30218.8652,
    "goodwill_pct_of_consideration": 59.0882,
    "new_intangibles": 16520.0
  },
  "projections": {
    "ambuja": {
      "revenue": [
        15656.48,
        17065.5632,
        18430.8083
      ],
      "ebitda": [
        2818.1664,
        3413.1126,
        3870.4697
      ],
      "depreciation": [
        618.24,
        673.8816,
        727.7921
      ],
      "treasury_income": [
        126.9609,
        126.9609,
        126.9609
      ],
      "interest_expense": [
        91.0,
        91.0,
        91.0
      ],
      "pbt": [
        2235.8873,
        2775.1919,
        3178.6385
      ],
      "tax": [
        562.7728,
        698.5158,
        800.0633
      ],
      "net_income": [
        1673.1144,
        2076.6761,
        2378.5752
      ],
      "da_pct_of_revenue": 3.9488
    },
    "acc": {
      "revenue": [
        18089.12,
        19717.1408,
        21294.5121
      ],
      "ebitda": [
        2170.6944,
        2760.3997,
        3194.1768
      ],
      "depreciation": [
        668.64,
        728.8176,
        787.123
      ],
      "treasury_income": [
        225.4477,
        225.4477,
        225.4477
      ],
      "interest_expense": [
        55.0,
        55.0,
        55.0
      ],
      "pbt": [
        1672.5021,
        2202.0298,
        2577.5015
      ],
      "tax": [
        420.9688,
        554.2509,
        648.7571
      ],
      "net_income": [
        1251.5333,
        1647.7789,
        1928.7444
      ],
      "da_pct_of_revenue": 3.6964
    },
    "dividends": {
      "acc_total": [
        250.3067,
        329.5558,
        385.7489
      ],
      "acc_to_ambuja": [
        125.2785,
        164.9427,
        193.0673
      ],
      "ambuja_total": [
        359.6786,
        448.3238,
        514.3285
      ]
    },
    "treasury_yield_pct": 3.0454,
    "acc_dividend_in_ambuja_cy2021": 131.5915
  },
  "synergies": {
    "items": {
      "procurement": {
        "label": "Procurement (fly ash, gypsum, slag, coal)",
        "type": "cost",
        "run_rate": 850.0,
        "by_year": [
          255.0,
          595.0,
          850.0
        ]
      },
      "logistics": {
        "label": "Logistics & freight (route rationalisation, ports)",
        "type": "cost",
        "run_rate": 620.0,
        "by_year": [
          124.0,
          372.0,
          620.0
        ]
      },
      "sga": {
        "label": "SG&A and shared services",
        "type": "cost",
        "run_rate": 480.0,
        "by_year": [
          192.0,
          384.0,
          480.0
        ]
      },
      "energy": {
        "label": "Energy (fuel mix, WHRS, renewables)",
        "type": "cost",
        "run_rate": 380.0,
        "by_year": [
          57.0,
          190.0,
          380.0
        ]
      },
      "plant": {
        "label": "Plant optimisation (clinker factor)",
        "type": "cost",
        "run_rate": 270.0,
        "by_year": [
          27.0,
          121.5,
          270.0
        ]
      },
      "geography": {
        "label": "Revenue: cross-selling into new regions (EBITDA impact)",
        "type": "revenue",
        "run_rate": 310.0,
        "by_year": [
          31.0,
          124.0,
          310.0
        ]
      },
      "pricing": {
        "label": "Revenue: pricing discipline (EBITDA impact)",
        "type": "revenue",
        "run_rate": 190.0,
        "by_year": [
          47.5,
          123.5,
          190.0
        ]
      }
    },
    "pretax_by_year": [
      733.5,
      1910.0,
      3100.0
    ],
    "after_tax_by_year": [
      548.8781,
      1429.253,
      2319.73
    ],
    "run_rate": 3100.0,
    "cost_run_rate": 2600.0,
    "revenue_run_rate": 500.0,
    "costs_to_achieve_by_year": [
      1680.0,
      1120.0,
      0.0
    ],
    "costs_to_achieve_total": 2800.0,
    "discount_rate_pct": 12.775,
    "terminal_growth_pct": 4.0,
    "pv_by_year": [
      486.7019,
      1123.7855,
      1617.3311
    ],
    "pv_terminal": 19168.3683,
    "gross_npv": 22396.1868,
    "pv_costs_to_achieve_after_tax": 1773.7101,
    "net_npv": 20622.4767,
    "terminal_value_share_pct": 85.5876,
    "gross_npv_per_rupee_of_run_rate": 7.2246
  },
  "pro_forma": [
    {
      "year": "FY2023E",
      "ambuja_revenue": 15656.48,
      "acc_revenue": 18089.12,
      "combined_revenue": 33745.6,
      "ambuja_ebitda": 2818.1664,
      "acc_ebitda": 2170.6944,
      "synergies": 733.5,
      "costs_to_achieve": 1680.0,
      "ebitda": 4042.3608,
      "ebitda_margin_pct": 11.9789,
      "standalone_da": 1286.88,
      "ppa_amortisation": 1568.0,
      "ebit": 1187.4808,
      "treasury_income": 352.4085,
      "target_interest": 146.0,
      "holdco_interest": 2834.675,
      "pbt": -1440.7857,
      "tax": 350.8419,
      "consolidated_net_income": -1791.6276,
      "blended_ownership_pct": 52.3127,
      "attributable_net_income": -2270.9267,
      "nci_net_income": 479.2991,
      "attributable_synergies_after_tax": 287.133,
      "attributable_ppa_after_tax": 600.9313,
      "attributable_costs_to_achieve_after_tax": 657.6461,
      "holdco_interest_after_shield": 2834.675,
      "dividends_received_net": 229.901,
      "holdco_cash_flow": -2604.774,
      "dividend_interest_cover": 0.0811,
      "sponsor_top_up": 2604.774,
      "debt_repayment": 0.0,
      "holdco_debt_open": 35932.5,
      "holdco_debt_close": 35932.5,
      "sponsor_equity_open": 15720.8481
    },
    {
      "year": "FY2024E",
      "ambuja_revenue": 17065.5632,
      "acc_revenue": 19717.1408,
      "combined_revenue": 36782.704,
      "ambuja_ebitda": 3413.1126,
      "acc_ebitda": 2760.3997,
      "synergies": 1910.0,
      "costs_to_achieve": 1120.0,
      "ebitda": 6963.5124,
      "ebitda_margin_pct": 18.9315,
      "standalone_da": 1402.6992,
      "ppa_amortisation": 1168.0,
      "ebit": 4392.8132,
      "treasury_income": 352.4085,
      "target_interest": 146.0,
      "holdco_interest": 2694.9375,
      "pbt": 1904.2842,
      "tax": 1157.6241,
      "consolidated_net_income": 746.6601,
      "blended_ownership_pct": 52.0132,
      "attributable_net_income": -898.7879,
      "nci_net_income": 1645.448,
      "attributable_synergies_after_tax": 743.4006,
      "attributable_ppa_after_tax": 452.9116,
      "attributable_costs_to_achieve_after_tax": 435.9208,
      "holdco_interest_after_shield": 2694.9375,
      "dividends_received_net": 287.5531,
      "holdco_cash_flow": -2407.3844,
      "dividend_interest_cover": 0.1067,
      "sponsor_top_up": 2407.3844,
      "debt_repayment": 0.0,
      "holdco_debt_open": 35932.5,
      "holdco_debt_close": 35932.5,
      "sponsor_equity_open": 18325.6221
    },
    {
      "year": "FY2025E",
      "ambuja_revenue": 18430.8083,
      "acc_revenue": 21294.5121,
      "combined_revenue": 39725.3203,
      "ambuja_ebitda": 3870.4697,
      "acc_ebitda": 3194.1768,
      "synergies": 3100.0,
      "costs_to_achieve": 0.0,
      "ebitda": 10164.6465,
      "ebitda_margin_pct": 25.5873,
      "standalone_da": 1514.9151,
      "ppa_amortisation": 1168.0,
      "ebit": 7481.7314,
      "treasury_income": 352.4085,
      "target_interest": 146.0,
      "holdco_interest": 2694.9375,
      "pbt": 4993.2024,
      "tax": 1935.1048,
      "consolidated_net_income": 3058.0976,
      "blended_ownership_pct": 51.8887,
      "attributable_net_income": 295.5118,
      "nci_net_income": 2762.5858,
      "attributable_synergies_after_tax": 1203.6788,
      "attributable_ppa_after_tax": 452.9116,
      "attributable_costs_to_achieve_after_tax": 0.0,
      "holdco_interest_after_shield": 2694.9375,
      "dividends_received_net": 330.3215,
      "holdco_cash_flow": -2364.616,
      "dividend_interest_cover": 0.1226,
      "sponsor_top_up": 2364.616,
      "debt_repayment": 0.0,
      "holdco_debt_open": 35932.5,
      "holdco_debt_close": 35932.5,
      "sponsor_equity_open": 20733.0065
    }
  ],
  "returns": [
    {
      "year": "FY2023E",
      "attributable_net_income": -2270.9267,
      "sponsor_equity_invested": 15720.8481,
      "roe_pct": -14.4453,
      "levered_cost_of_equity_pct": 25.8279,
      "earns_cost_of_equity": false,
      "cash_earnings_pre_financing": 1822.3256,
      "cash_roic_pct": 3.528,
      "cash_roic_ex_synergies_pct": 2.9721,
      "unlevered_cost_of_capital_pct": 12.775,
      "earns_cost_of_capital": false,
      "breakeven_synergies_for_roic": 12935.0995,
      "dividend_interest_cover": 0.0811
    },
    {
      "year": "FY2024E",
      "attributable_net_income": -898.7879,
      "sponsor_equity_invested": 18325.6221,
      "roe_pct": -4.9045,
      "levered_cost_of_equity_pct": 25.8279,
      "earns_cost_of_equity": false,
      "cash_earnings_pre_financing": 2684.982,
      "cash_roic_pct": 5.1981,
      "cash_roic_ex_synergies_pct": 3.7589,
      "unlevered_cost_of_capital_pct": 12.775,
      "earns_cost_of_capital": false,
      "breakeven_synergies_for_roic": 11965.4537,
      "dividend_interest_cover": 0.1067
    },
    {
      "year": "FY2025E",
      "attributable_net_income": 295.5118,
      "sponsor_equity_invested": 20733.0065,
      "roe_pct": 1.4253,
      "levered_cost_of_equity_pct": 25.8279,
      "earns_cost_of_equity": false,
      "cash_earnings_pre_financing": 3443.3609,
      "cash_roic_pct": 6.6663,
      "cash_roic_ex_synergies_pct": 4.336,
      "unlevered_cost_of_capital_pct": 12.775,
      "earns_cost_of_capital": false,
      "breakeven_synergies_for_roic": 11226.419,
      "dividend_interest_cover": 0.1226
    }
  ],
  "value_creation": {
    "adani_share_of_synergies_pct": 51.8887,
    "adani_share_of_net_synergy_npv": 10700.7447,
    "premium_paid": 3480.3412,
    "transaction_costs": 511.4193,
    "premium_plus_costs": 3991.7605,
    "net_value_created": 6708.9841,
    "breakeven_run_rate_synergies": 1310.3373,
    "synergy_cushion_vs_breakeven_pct": 136.5803
  },
  "balance_sheet": {
    "assets": {
      "fixed_assets_and_cwip": 22557.0,
      "acquired_intangibles": 16520.0,
      "goodwill": 30218.8652,
      "inventories": 3137.0,
      "trade_receivables": 757.0,
      "cash": 11572.0,
      "investments": 193.0,
      "other_assets": 5512.0
    },
    "liabilities": {
      "acquisition_debt": 35932.5,
      "target_borrowings_and_leases": 477.0,
      "deferred_tax_on_step_ups": 5768.964,
      "other_liabilities": 12192.0
    },
    "equity": {
      "adani_equity": 15209.4289,
      "non_controlling_interests": 20886.9724
    },
    "total_assets": 90466.8652,
    "total_liabilities_and_equity": 90466.8652,
    "credit_at_close": {
      "gross_debt": 36409.5,
      "net_debt": 24837.5,
      "ebitda_cy2021": 6215.0,
      "gross_debt_to_ebitda": 5.8583,
      "net_debt_to_ebitda": 3.9964,
      "holdco_ltv_at_cost_pct": 70.2604,
      "holdco_ltv_at_completion_market_pct": 52.8081
    },
    "credit_by_year": [
      {
        "year": "FY2023E",
        "gross_debt": 36409.5,
        "net_debt": 24837.5,
        "net_debt_to_ebitda": 6.1443,
        "ebitda_interest_cover": 1.3562
      },
      {
        "year": "FY2024E",
        "gross_debt": 36409.5,
        "net_debt": 24837.5,
        "net_debt_to_ebitda": 3.5668,
        "ebitda_interest_cover": 2.4511
      },
      {
        "year": "FY2025E",
        "gross_debt": 36409.5,
        "net_debt": 24837.5,
        "net_debt_to_ebitda": 2.4435,
        "ebitda_interest_cover": 3.5779
      }
    ]
  },
  "valuation": {
    "equity_value_at_offer": 98021.003,
    "net_debt_cy2021": -11095.0,
    "enterprise_value": 86926.003,
    "ebitda_cy2021": 6215.0,
    "ev_to_ebitda_cy2021": 13.9865,
    "ev_to_ebitda_fy2023e": 17.424,
    "capacity_mtpa": 67.5,
    "ev_per_tonne_inr": 12877.9264,
    "ev_per_tonne_usd": 161.2765
  },
  "precedents": {
    "rows": [
      {
        "date": "Sep-2013",
        "acquirer": "UltraTech Cement",
        "target": "Jaypee Gujarat unit",
        "capacity_mtpa": 4.8,
        "ev_cr": 3800.0,
        "inr_per_usd": 63.16,
        "note": "",
        "source": "bs_jaypee_2013",
        "ev_per_tonne_inr": 7916.6667,
        "ev_per_tonne_usd": 125.343,
        "distressed": false,
        "source_text": "Business Standard, 12-Sep-2013 — https://www.business-standard.com/article/companies/birla-buys-jaypee-s-gujarat-cement-unit-for-rs-3-800-cr-113091200054_1.html"
      },
      {
        "date": "Mar-2016",
        "acquirer": "UltraTech Cement",
        "target": "Jaiprakash Associates (6 plants)",
        "capacity_mtpa": 21.2,
        "ev_cr": 16189.0,
        "inr_per_usd": 66.37,
        "note": "Seller deleveraging; EV as revised from ₹15,900 Cr",
        "source": "bs_jaypee_2016",
        "ev_per_tonne_inr": 7636.3208,
        "ev_per_tonne_usd": 115.0568,
        "distressed": false,
        "source_text": "Business Standard, 5-Jul-2016 — https://www.business-standard.com/article/markets/jp-deal-big-leap-for-ultratech-116070501043_1.html"
      },
      {
        "date": "Jul-2016",
        "acquirer": "Nirma",
        "target": "Lafarge India",
        "capacity_mtpa": 11.0,
        "ev_cr": 9400.0,
        "inr_per_usd": 67.13,
        "note": "",
        "source": "bs_lafarge_2016",
        "ev_per_tonne_inr": 8545.4545,
        "ev_per_tonne_usd": 127.2971,
        "distressed": false,
        "source_text": "Business Standard, 11-Jul-2016 — https://www.business-standard.com/article/companies/nirma-cements-1-4-bn-lafarge-india-buyout-116071100403_1.html"
      },
      {
        "date": "May-2018",
        "acquirer": "UltraTech Cement",
        "target": "Century Textiles (cement)",
        "capacity_mtpa": 14.6,
        "ev_cr": 8621.0,
        "inr_per_usd": 67.97,
        "note": "",
        "source": "li_century_2018",
        "ev_per_tonne_inr": 5904.7945,
        "ev_per_tonne_usd": 86.8735,
        "distressed": false,
        "source_text": "Legally India, 22-May-2018 (EV) — https://www.legallyindia.com/corporatemna/trilegal-khaitan-vaish-on-ultratech-cem-s-buy-of-century-textile-s-cement-biz-20180522-9362 ; capacity per CARE Ratings report on UltraTech"
      },
      {
        "date": "Nov-2018",
        "acquirer": "UltraTech Cement",
        "target": "Binani Cement",
        "capacity_mtpa": 11.0,
        "ev_cr": 7900.0,
        "inr_per_usd": 71.69,
        "note": "Distressed (IBC); capacity incl. ~5 MTPA overseas",
        "source": "bs_binani_2018",
        "distressed": true,
        "ev_per_tonne_inr": 7181.8182,
        "ev_per_tonne_usd": 100.1788,
        "source_text": "Business Standard, 25-Dec-2019 (Kotak estimate of EV) — https://www.business-standard.com/amp/article/companies/ultratech-cement-street-watchful-on-valuations-of-new-acquisition-119122500555_1.html"
      },
      {
        "date": "Feb-2020",
        "acquirer": "Nuvoco Vistas (Nirma)",
        "target": "Emami Cement",
        "capacity_mtpa": 8.3,
        "ev_cr": 5500.0,
        "inr_per_usd": 71.28,
        "note": "",
        "source": "nuvoco_emami_2020",
        "ev_per_tonne_inr": 6626.506,
        "ev_per_tonne_usd": 92.9645,
        "distressed": false,
        "source_text": "Nuvoco press release, Feb-2020 — https://admin.nuvoco.com/public/MediaRalationsDetails/Nirma%20Group%20announces%20the%20acquisition%20of%20Emami%20Cement%20-%20Feb%202020.pdf"
      }
    ],
    "count": 6,
    "count_ex_distressed": 5,
    "mean_usd_per_t": 107.9523,
    "median_usd_per_t": 107.6178,
    "mean_usd_per_t_ex_distressed": 109.507,
    "median_usd_per_t_ex_distressed": 115.0568,
    "this_deal_usd_per_t": 161.2765,
    "this_deal_premium_to_median_ex_distressed_pct": 40.1712
  },
  "sensitivity": {
    "final_year": "FY2025E",
    "offer_price": [
      {
        "price_multiplier": 0.95,
        "ambuja_offer_price": 365.75,
        "ambuja_premium_pct": 1.8519,
        "total_consideration": 48584.8324,
        "sponsor_equity": 13138.1807,
        "goodwill": 27661.7688,
        "cash_roic_final_year_pct": 7.0171,
        "roe_final_year_pct": 1.6281,
        "net_value_created": 9291.6516
      },
      {
        "price_multiplier": 1.0,
        "ambuja_offer_price": 385.0,
        "ambuja_premium_pct": 7.2125,
        "total_consideration": 51141.9289,
        "sponsor_equity": 15720.8481,
        "goodwill": 30218.8652,
        "cash_roic_final_year_pct": 6.6663,
        "roe_final_year_pct": 1.4253,
        "net_value_created": 6708.9841
      },
      {
        "price_multiplier": 1.05,
        "ambuja_offer_price": 404.25,
        "ambuja_premium_pct": 12.5731,
        "total_consideration": 53699.0253,
        "sponsor_equity": 18303.5156,
        "goodwill": 32775.9617,
        "cash_roic_final_year_pct": 6.3488,
        "roe_final_year_pct": 1.2674,
        "net_value_created": 4126.3167
      },
      {
        "price_multiplier": 1.1,
        "ambuja_offer_price": 423.5,
        "ambuja_premium_pct": 17.9337,
        "total_consideration": 56256.1217,
        "sponsor_equity": 20886.183,
        "goodwill": 35333.0581,
        "cash_roic_final_year_pct": 6.0603,
        "roe_final_year_pct": 1.141,
        "net_value_created": 1543.6493
      },
      {
        "price_multiplier": 1.15,
        "ambuja_offer_price": 442.75,
        "ambuja_premium_pct": 23.2943,
        "total_consideration": 58813.2182,
        "sponsor_equity": 23468.8504,
        "goodwill": 37890.1546,
        "cash_roic_final_year_pct": 5.7968,
        "roe_final_year_pct": 1.0376,
        "net_value_created": -1039.0181
      },
      {
        "price_multiplier": 1.2,
        "ambuja_offer_price": 462.0,
        "ambuja_premium_pct": 28.655,
        "total_consideration": 61370.3146,
        "sponsor_equity": 26051.5178,
        "goodwill": 40447.251,
        "cash_roic_final_year_pct": 5.5552,
        "roe_final_year_pct": 0.9513,
        "net_value_created": -3621.6855
      }
    ],
    "refi_rate": [
      {
        "refi_rate_pct": 6.0,
        "holdco_interest_final_year": 2155.95,
        "attributable_ni_final_year": 834.4993,
        "roe_final_year_pct": 4.1324,
        "dividend_interest_cover_final_year": 0.1532
      },
      {
        "refi_rate_pct": 6.5,
        "holdco_interest_final_year": 2335.6125,
        "attributable_ni_final_year": 654.8368,
        "roe_final_year_pct": 3.2141,
        "dividend_interest_cover_final_year": 0.1414
      },
      {
        "refi_rate_pct": 7.0,
        "holdco_interest_final_year": 2515.275,
        "attributable_ni_final_year": 475.1743,
        "roe_final_year_pct": 2.3119,
        "dividend_interest_cover_final_year": 0.1313
      },
      {
        "refi_rate_pct": 7.5,
        "holdco_interest_final_year": 2694.9375,
        "attributable_ni_final_year": 295.5118,
        "roe_final_year_pct": 1.4253,
        "dividend_interest_cover_final_year": 0.1226
      },
      {
        "refi_rate_pct": 8.0,
        "holdco_interest_final_year": 2874.6,
        "attributable_ni_final_year": 115.8493,
        "roe_final_year_pct": 0.554,
        "dividend_interest_cover_final_year": 0.1149
      },
      {
        "refi_rate_pct": 8.5,
        "holdco_interest_final_year": 3054.2625,
        "attributable_ni_final_year": -63.8132,
        "roe_final_year_pct": -0.3025,
        "dividend_interest_cover_final_year": 0.1082
      },
      {
        "refi_rate_pct": 9.0,
        "holdco_interest_final_year": 3233.925,
        "attributable_ni_final_year": -243.4757,
        "roe_final_year_pct": -1.1446,
        "dividend_interest_cover_final_year": 0.1021
      },
      {
        "refi_rate_pct": 9.5,
        "holdco_interest_final_year": 3413.5875,
        "attributable_ni_final_year": -423.1382,
        "roe_final_year_pct": -1.9725,
        "dividend_interest_cover_final_year": 0.0968
      }
    ],
    "synergy_levels": [
      0,
      1000,
      2000,
      3100,
      4000,
      5000
    ],
    "matrix_net_value_created": [
      {
        "price_multiplier": 0.95,
        "0": -2329.4491,
        "1000": 1419.2931,
        "2000": 5168.0352,
        "3100": 9291.6516,
        "4000": 12665.5195,
        "5000": 16414.2616
      },
      {
        "price_multiplier": 1.0,
        "0": -4912.1165,
        "1000": -1163.3743,
        "2000": 2585.3678,
        "3100": 6708.9841,
        "4000": 10082.8521,
        "5000": 13831.5942
      },
      {
        "price_multiplier": 1.05,
        "0": -7494.7839,
        "1000": -3746.0417,
        "2000": 2.7004,
        "3100": 4126.3167,
        "4000": 7500.1847,
        "5000": 11248.9268
      },
      {
        "price_multiplier": 1.1,
        "0": -10077.4513,
        "1000": -6328.7091,
        "2000": -2579.967,
        "3100": 1543.6493,
        "4000": 4917.5173,
        "5000": 8666.2594
      },
      {
        "price_multiplier": 1.15,
        "0": -12660.1187,
        "1000": -8911.3766,
        "2000": -5162.6344,
        "3100": -1039.0181,
        "4000": 2334.8498,
        "5000": 6083.592
      },
      {
        "price_multiplier": 1.2,
        "0": -15242.7861,
        "1000": -11494.044,
        "2000": -7745.3018,
        "3100": -3621.6855,
        "4000": -247.8176,
        "5000": 3500.9246
      }
    ],
    "matrix_cash_roic_final_year": [
      {
        "price_multiplier": 0.95,
        "0": 4.5642,
        "1000": 5.3555,
        "2000": 6.1467,
        "3100": 7.0171,
        "4000": 7.7293,
        "5000": 8.5206
      },
      {
        "price_multiplier": 1.0,
        "0": 4.336,
        "1000": 5.0877,
        "2000": 5.8394,
        "3100": 6.6663,
        "4000": 7.3428,
        "5000": 8.0945
      },
      {
        "price_multiplier": 1.05,
        "0": 4.1295,
        "1000": 4.8454,
        "2000": 5.5613,
        "3100": 6.3488,
        "4000": 6.9932,
        "5000": 7.7091
      },
      {
        "price_multiplier": 1.1,
        "0": 3.9418,
        "1000": 4.6252,
        "2000": 5.3086,
        "3100": 6.0603,
        "4000": 6.6753,
        "5000": 7.3587
      },
      {
        "price_multiplier": 1.15,
        "0": 3.7704,
        "1000": 4.4241,
        "2000": 5.0777,
        "3100": 5.7968,
        "4000": 6.3851,
        "5000": 7.0387
      },
      {
        "price_multiplier": 1.2,
        "0": 3.6133,
        "1000": 4.2397,
        "2000": 4.8662,
        "3100": 5.5552,
        "4000": 6.119,
        "5000": 6.7454
      }
    ],
    "ebitda_margin": [
      {
        "margin_change_bp": -300,
        "cash_roic_final_year_pct": 5.8255,
        "roe_final_year_pct": -0.6658
      },
      {
        "margin_change_bp": -200,
        "cash_roic_final_year_pct": 6.105,
        "roe_final_year_pct": 0.0268
      },
      {
        "margin_change_bp": -100,
        "cash_roic_final_year_pct": 6.3853,
        "roe_final_year_pct": 0.724
      },
      {
        "margin_change_bp": 0,
        "cash_roic_final_year_pct": 6.6663,
        "roe_final_year_pct": 1.4253
      },
      {
        "margin_change_bp": 100,
        "cash_roic_final_year_pct": 6.9479,
        "roe_final_year_pct": 2.1306
      },
      {
        "margin_change_bp": 200,
        "cash_roic_final_year_pct": 7.23,
        "roe_final_year_pct": 2.8396
      },
      {
        "margin_change_bp": 300,
        "cash_roic_final_year_pct": 7.5125,
        "roe_final_year_pct": 3.5521
      }
    ],
    "interest_tax_shield": [
      {
        "interest_tax_deductible": false,
        "attributable_ni_final_year": 295.5118,
        "roe_final_year_pct": 1.4253,
        "levered_cost_of_equity_pct": 25.8279
      },
      {
        "interest_tax_deductible": true,
        "attributable_ni_final_year": 973.8276,
        "roe_final_year_pct": 5.035,
        "levered_cost_of_equity_pct": 22.5425
      }
    ]
  },
  "sources": {
    "holcim_release": "Holcim media release, May-2022 — https://www.holcim.com/media/media-releases/holcim-india-business-acquired",
    "adani_release": "Adani media release, 16-Sep-2022 — https://www.adani.com/newsroom/media-releases/adani-becomes-indias-second-largest-cement-player",
    "bs_open_offer": "Business Standard, 10-Sep-2022 — https://www.business-standard.com/article/companies/ambuja-cements-acc-receive-lukewarm-response-from-public-shareholders-122091000362_1.html",
    "bs_refi": "Business Standard, 1-Dec-2022 — https://www.business-standard.com/article/companies/adani-group-to-refinance-ambuja-cement-acc-debt-worth-3-5-billion-122120100944_1.html",
    "screener_ambuja": "Ambuja standalone financials (company filings via Screener) — https://www.screener.in/company/AMBUJACEM/",
    "screener_acc": "ACC standalone financials (company filings via Screener) — https://www.screener.in/company/ACC/",
    "nse_prices": "NSE daily closes (Yahoo Finance history: AMBUJACEM.NS, ACC.NS, USDINR=X)",
    "bs_jaypee_2013": "Business Standard, 12-Sep-2013 — https://www.business-standard.com/article/companies/birla-buys-jaypee-s-gujarat-cement-unit-for-rs-3-800-cr-113091200054_1.html",
    "bs_jaypee_2016": "Business Standard, 5-Jul-2016 — https://www.business-standard.com/article/markets/jp-deal-big-leap-for-ultratech-116070501043_1.html",
    "bs_lafarge_2016": "Business Standard, 11-Jul-2016 — https://www.business-standard.com/article/companies/nirma-cements-1-4-bn-lafarge-india-buyout-116071100403_1.html",
    "li_century_2018": "Legally India, 22-May-2018 (EV) — https://www.legallyindia.com/corporatemna/trilegal-khaitan-vaish-on-ultratech-cem-s-buy-of-century-textile-s-cement-biz-20180522-9362 ; capacity per CARE Ratings report on UltraTech",
    "bs_binani_2018": "Business Standard, 25-Dec-2019 (Kotak estimate of EV) — https://www.business-standard.com/amp/article/companies/ultratech-cement-street-watchful-on-valuations-of-new-acquisition-119122500555_1.html",
    "nuvoco_emami_2020": "Nuvoco press release, Feb-2020 — https://admin.nuvoco.com/public/MediaRalationsDetails/Nirma%20Group%20announces%20the%20acquisition%20of%20Emami%20Cement%20-%20Feb%202020.pdf"
  },
  "narrative": {
    "verdict_title": "The premium is covered by synergies, but earnings returns trail the cost of capital and the holdco cannot service its debt from dividends",
    "value_line": "Adani's share of the net synergy NPV is ₹10,701 Cr against ₹3,992 Cr of premium and transaction costs, creating ₹6,709 Cr of value. Breakeven run-rate synergies are ₹1,310 Cr versus ₹3,100 Cr modelled.",
    "returns_line": "Cash ROIC on the ₹51,653 Cr invested reaches 6.7% by FY2025E, below the 12.78% unlevered cost of capital; return on sponsor equity is 1.4% against a 25.8% levered cost of equity. The price is 14.0x CY2021 EBITDA, so near-term earnings yields are low.",
    "holdco_line": "Dividends received cover 0.12x of holdco interest in FY2025E; the shortfall of ₹2,365 Cr a year must come from refinancing, asset sales or sponsor equity.",
    "precedent_line": "At US$161/tonne, the deal is 40% above the median of 5 non-distressed Indian cement precedents (US$115/t), consistent with buying a pan-India, net-cash, two-brand platform rather than single assets.",
    "recommendation": "Proceed only with (1) committed refinancing or sponsor support for holdco interest, which dividends do not cover; (2) a synergy plan tracked against the ₹1,310 Cr breakeven; and (3) acceptance that earnings returns stay below the cost of capital through the projection period."
  }
};
